//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.ArtistApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_AS_Artist_Event : Entity
    {
        public int Event_ID { get; set; }
        public int Artist_ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Event_Type_LKP_ID { get; set; }
        public System.DateTime Start_Time { get; set; }
        public System.DateTime End_Time { get; set; }
        public string Reference_ID { get; set; }
        public Nullable<int> Status_LKP_ID { get; set; }
        public string UDF { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public string Last_Updated_By { get; set; }
        public bool Active_Flag { get; set; }
    
        public virtual NAT_AS_Artist NAT_AS_Artist { get; set; }
    }
}
