//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.ArtistApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_AS_Artist_Address_Geography : Entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NAT_AS_Artist_Address_Geography()
        {
            this.NAT_AS_Artist_Address_Geography1 = new HashSet<NAT_AS_Artist_Address_Geography>();
        }
    
        public int Address_Geography_ID { get; set; }
        public Nullable<int> Parent_Geography_ID { get; set; }
        public string Geography_Description { get; set; }
        public Nullable<int> Geography_Short_Code { get; set; }
        public Nullable<int> Geography_Type_LKP_ID { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public string Last_Updated_By { get; set; }
        public bool Active_Flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_AS_Artist_Address_Geography> NAT_AS_Artist_Address_Geography1 { get; set; }
        public virtual NAT_AS_Artist_Address_Geography NAT_AS_Artist_Address_Geography2 { get; set; }
    }
}
