//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.ArtistApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_AS_Artist_Venue_Preference : Entity
    {
        public int Venue_Preference_ID { get; set; }
        public bool Active_Flag { get; set; }
        public int Venue_ID { get; set; }
        public int Artist_ID { get; set; }
    
        public virtual NAT_AS_Artist NAT_AS_Artist { get; set; }
    }
}
