//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.ArtistApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_Artist_VW : Entity
    {
        public int Artist_ID { get; set; }
        public string Stage_Name { get; set; }
        public string STATUS { get; set; }
        public string Artist_First_Name { get; set; }
        public string Artist_Middle_Name { get; set; }
        public string Artist_Last_Name { get; set; }
        public string Location_Code { get; set; }
        public string Artist_Stage_Name_ID { get; set; }
        public string Market_Code { get; set; }
        public string Artist_Email { get; set; }
        public string Artist_Phone_Number { get; set; }
        public string Next_Event_Confirmed { get; set; }
        public Nullable<System.DateTime> Next_Event_Date { get; set; }
        public Nullable<System.DateTime> Next_Event_End_Time { get; set; }
        public string Next_Event_Location_Code { get; set; }
        public string Next_Event_Venue_ID { get; set; }
        public string Next_Event_Description { get; set; }
        public Nullable<System.DateTime> Last_Event_Date { get; set; }
        public Nullable<System.DateTime> Last_Event_End_Time { get; set; }
        public string Last_Event_Location_Code { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public string Last_Updated_By { get; set; }
        public string Company_Name { get; set; }
        public string Company_Email { get; set; }
        public string Company_Phone { get; set; }
        public string Onboarded { get; set; }
        public string Emergency_Contact_Name { get; set; }
        public string Emergency_Contact { get; set; }
        public string Emergency_Contact_Email { get; set; }
        public string Emergency_Contact_Relationship { get; set; }
        public string Artist_About { get; set; }
        public string Tax_Number { get; set; }
        public string SIN { get; set; }
        public string Notes { get; set; }
        public string Artist_Address { get; set; }
        public string Postal_Zip_Code { get; set; }
        public string Artist_City_Name { get; set; }
        public string Artist_State_Name { get; set; }
        public string Artist_Country_Name { get; set; }
        public string Next_Event_Venue_Name { get; set; }
    }
}
