//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.ArtistApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_AS_Artist_Bank_Account : Entity
    {
        public int Artist_Bank_Account_ID { get; set; }
        public Nullable<int> Artist_ID { get; set; }
        public string Bank_Routing_Number { get; set; }
        public Nullable<System.DateTime> Effective_Start_Date { get; set; }
        public Nullable<System.DateTime> Effective_End_Date { get; set; }
        public string Bank_LKP_ID { get; set; }
        public string Bank_Account_Number { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public string Last_Updated_By { get; set; }
        public bool Active_Flag { get; set; }
        public Nullable<int> Address_ID { get; set; }
        public string Bank_Type_LKP_ID { get; set; }
        public string Bank_Code { get; set; }
        public string Transit_Number { get; set; }
        public string Institution_Code { get; set; }
    
        public virtual NAT_AS_Artist NAT_AS_Artist { get; set; }
        public virtual NAT_AS_Artist_Address NAT_AS_Artist_Address { get; set; }
    }
}
