//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.PlannerApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_PLS_Slot : Entity
    {
        public int Slot_ID { get; set; }
        public int Planner_ID { get; set; }
        public Nullable<int> Event_ID { get; set; }
        public string Description { get; set; }
        public System.DateTime Start_Time { get; set; }
        public System.DateTime End_Time { get; set; }
        public int Status_Type_LKP_ID { get; set; }
        public int Slot_Type_LKP_ID { get; set; }
        public bool Active_Flag { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Last_Updated_By { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public string Event_Name { get; set; }
        public string Timing_LKP { get; set; }
    
        public virtual NAT_PLS_Planner NAT_PLS_Planner { get; set; }
        public virtual NAT_PLS_Event NAT_PLS_Event { get; set; }
    }
}
