//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.PlannerApp.Models.EFModel
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class PlannerEntities : ElasticScaleContext
    {		
    private void Initialize(){
    			}
    
        private PlannerEntities(string connectionStringName)
            : base(connectionStringName)
        {
    		Initialize();
        }
    
    	private PlannerEntities()
            : base()
        {
    		Initialize();
        }
    
    	public static PlannerEntities CreateContext(bool isMultitenancyEnabled = false)
    	{
    		if(isMultitenancyEnabled)	
    		{
    			return new PlannerEntities();
    		}
    		else
    		{
    			return new PlannerEntities(ConfigurationManager.ConnectionStrings["PlannerEntities"].ConnectionString);
    		}
    	}		
    
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NAT_PLS_Availability> NAT_PLS_Availability { get; set; }
        public virtual DbSet<NAT_PLS_Availability_Slot> NAT_PLS_Availability_Slot { get; set; }
        public virtual DbSet<NAT_PLS_Event> NAT_PLS_Event { get; set; }
        public virtual DbSet<NAT_PLS_Planner> NAT_PLS_Planner { get; set; }
        public virtual DbSet<NAT_PLS_Slot> NAT_PLS_Slot { get; set; }
    }
}
