//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.VenueApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_VS_Venue_Contact_Person : Entity
    {
        public int Venue_Contact_Person_ID { get; set; }
        public Nullable<int> Venue_ID { get; set; }
        public Nullable<System.DateTime> Effective_Start_Date { get; set; }
        public Nullable<System.DateTime> Effective_End_Date { get; set; }
        public string Extension { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Profile_Image_Link { get; set; }
        public string Email { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public Nullable<int> Billing_Address_ID { get; set; }
        public Nullable<int> Residential_Address_ID { get; set; }
        public Nullable<int> Gender_LKP_ID { get; set; }
        public Nullable<int> Shipping_Address_ID { get; set; }
        public string Contact_Number { get; set; }
        public Nullable<bool> Primary_VCP { get; set; }
        public string Designation { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public string Last_Updated_By { get; set; }
        public bool Active_Flag { get; set; }
        public Nullable<bool> Text_Flag { get; set; }
        public string Greeting { get; set; }
        public string Notes { get; set; }
    
        public virtual NAT_VS_Venue NAT_VS_Venue { get; set; }
        public virtual NAT_VS_Venue_Address NAT_VS_Venue_Address { get; set; }
        public virtual NAT_VS_Venue_Address NAT_VS_Venue_Address1 { get; set; }
        public virtual NAT_VS_Venue_Address NAT_VS_Venue_Address2 { get; set; }
    }
}
