//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.VenueApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_VS_Venue_Bank_Account : Entity
    {
        public int Venue_Bank_Account_ID { get; set; }
        public Nullable<int> Venue_ID { get; set; }
        public string Bank_Routing_Number { get; set; }
        public Nullable<System.DateTime> Effective_Start_Date { get; set; }
        public Nullable<System.DateTime> Effective_End_Date { get; set; }
        public string Bank_LKP_ID { get; set; }
        public string Bank_Account_Number { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public string Last_Updated_By { get; set; }
        public bool Active_Flag { get; set; }
        public Nullable<int> Address_ID { get; set; }
        public string Transit_Number { get; set; }
        public string Institutional_Number { get; set; }
        public string Account_Type { get; set; }
        public string Account_Name { get; set; }
    
        public virtual NAT_VS_Venue NAT_VS_Venue { get; set; }
        public virtual NAT_VS_Venue_Address NAT_VS_Venue_Address { get; set; }
    }
}
