//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.VenueApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_VS_Venue : Entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NAT_VS_Venue()
        {
            this.NAT_VS_Venue_Facility = new HashSet<NAT_VS_Venue_Facility>();
            this.NAT_VS_Venue_Hall = new HashSet<NAT_VS_Venue_Hall>();
            this.NAT_VS_Venue_Event = new HashSet<NAT_VS_Venue_Event>();
            this.NAT_VS_Venue_Rating = new HashSet<NAT_VS_Venue_Rating>();
            this.NAT_VS_Venue_Image = new HashSet<NAT_VS_Venue_Image>();
            this.NAT_VS_Venue_Rating_Log = new HashSet<NAT_VS_Venue_Rating_Log>();
            this.NAT_VS_Venue_Contact_Person = new HashSet<NAT_VS_Venue_Contact_Person>();
            this.NAT_VS_Venue_Document = new HashSet<NAT_VS_Venue_Document>();
            this.NAT_VS_Venue_Artist_Preference = new HashSet<NAT_VS_Venue_Artist_Preference>();
            this.NAT_VS_Venue_Bank_Account = new HashSet<NAT_VS_Venue_Bank_Account>();
            this.NAT_VS_Venue_Metro_City_Mapping = new HashSet<NAT_VS_Venue_Metro_City_Mapping>();
        }
    
        public int Venue_ID { get; set; }
        public Nullable<int> Address_ID { get; set; }
        public string Venue_Category_LKP_ID { get; set; }
        public string Venue_Status_LKP_ID { get; set; }
        public string Venue_Name { get; set; }
        public Nullable<int> Min_Seating_Capacity { get; set; }
        public Nullable<int> Max_Seating_Capacity { get; set; }
        public string Venue_Tags { get; set; }
        public string Venue_Image_Url { get; set; }
        public string Verified_Flag { get; set; }
        public Nullable<System.DateTime> Effective_Start_Date { get; set; }
        public Nullable<System.DateTime> Effective_End_Date { get; set; }
        public Nullable<int> Planner_ID { get; set; }
        public string Location_Code { get; set; }
        public Nullable<decimal> Hours_Per_Week { get; set; }
        public string Facebook_Profile_Url { get; set; }
        public string Twitter_Profile_Url { get; set; }
        public string Instagram_Profile_Url { get; set; }
        public string Google_Profile_Url { get; set; }
        public string Email { get; set; }
        public string Contact_Number { get; set; }
        public bool Virtual { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public string Last_Updated_By { get; set; }
        public bool Active_Flag { get; set; }
        public string SIN { get; set; }
        public string Tax_Number { get; set; }
        public string Payment_Cycle_LKP_ID { get; set; }
        public string Company_Name { get; set; }
        public string Special_Instr { get; set; }
        public string Notes { get; set; }
        public string Biz_Number { get; set; }
        public string Venue_URl { get; set; }
        public string Onboarded { get; set; }
        public string V_Event_Description { get; set; }
        public string Google_Map_URL { get; set; }
        public string Company_Number { get; set; }
        public string Company_Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_VS_Venue_Facility> NAT_VS_Venue_Facility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_VS_Venue_Hall> NAT_VS_Venue_Hall { get; set; }
        public virtual NAT_VS_Venue_Address NAT_VS_Venue_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_VS_Venue_Event> NAT_VS_Venue_Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_VS_Venue_Rating> NAT_VS_Venue_Rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_VS_Venue_Image> NAT_VS_Venue_Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_VS_Venue_Rating_Log> NAT_VS_Venue_Rating_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_VS_Venue_Contact_Person> NAT_VS_Venue_Contact_Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_VS_Venue_Document> NAT_VS_Venue_Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_VS_Venue_Artist_Preference> NAT_VS_Venue_Artist_Preference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_VS_Venue_Bank_Account> NAT_VS_Venue_Bank_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_VS_Venue_Metro_City_Mapping> NAT_VS_Venue_Metro_City_Mapping { get; set; }
    }
}
