//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.VenueApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_VS_Venue_Address : Entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NAT_VS_Venue_Address()
        {
            this.NAT_VS_Venue = new HashSet<NAT_VS_Venue>();
            this.NAT_VS_Venue_Contact_Person = new HashSet<NAT_VS_Venue_Contact_Person>();
            this.NAT_VS_Venue_Contact_Person1 = new HashSet<NAT_VS_Venue_Contact_Person>();
            this.NAT_VS_Venue_Contact_Person2 = new HashSet<NAT_VS_Venue_Contact_Person>();
            this.NAT_VS_Venue_Bank_Account = new HashSet<NAT_VS_Venue_Bank_Account>();
        }
    
        public int Address_ID { get; set; }
        public string Address_Line_1 { get; set; }
        public string Address_Line_2 { get; set; }
        public string Postal_Zip_Code { get; set; }
        public string City_Name { get; set; }
        public Nullable<int> Address_Geography_ID { get; set; }
        public System.Data.Entity.Spatial.DbGeography Coordinates { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public string Last_Updated_By { get; set; }
        public bool Active_Flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_VS_Venue> NAT_VS_Venue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_VS_Venue_Contact_Person> NAT_VS_Venue_Contact_Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_VS_Venue_Contact_Person> NAT_VS_Venue_Contact_Person1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_VS_Venue_Contact_Person> NAT_VS_Venue_Contact_Person2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_VS_Venue_Bank_Account> NAT_VS_Venue_Bank_Account { get; set; }
    }
}
