//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.VenueApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_VS_Venue_Seating_Plan : Entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NAT_VS_Venue_Seating_Plan()
        {
            this.NAT_VS_Venue_Seat = new HashSet<NAT_VS_Venue_Seat>();
        }
    
        public int Seating_Plan_ID { get; set; }
        public Nullable<int> Venue_Hall_ID { get; set; }
        public string Event_Seating_Plan_Name { get; set; }
        public Nullable<int> Total_Seats { get; set; }
        public Nullable<System.DateTime> Effective_Start_Date { get; set; }
        public Nullable<System.DateTime> Effective_End_Date { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public string Last_Updated_By { get; set; }
        public bool Active_Flag { get; set; }
        public Nullable<bool> Default_Plan { get; set; }
        public string Background_Image { get; set; }
        public Nullable<bool> Tax_Flag { get; set; }
        public Nullable<decimal> Gold_Price { get; set; }
        public Nullable<decimal> Silver_Price { get; set; }
        public Nullable<decimal> Basic_Price { get; set; }
        public Nullable<decimal> Extra_Price { get; set; }
        public string Notes { get; set; }
    
        public virtual NAT_VS_Venue_Hall NAT_VS_Venue_Hall { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_VS_Venue_Seat> NAT_VS_Venue_Seat { get; set; }
    }
}
