

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nat.LocationApp.Models.EFModel
{

using System;
using System.Configuration;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using TLX.CloudCore.Patterns.Repository.Ef6;


public partial class LocationEntities : ElasticScaleContext
{		
private void Initialize(){
		
	}

    private LocationEntities(string connectionStringName)
        : base(connectionStringName)
    {
		Initialize();
    }

	private LocationEntities()
        : base()
    {
		Initialize();
    }

	public static LocationEntities CreateContext(bool isMultitenancyEnabled = false)
	{
		if(isMultitenancyEnabled)	
		{
			return new LocationEntities();
		}
		else
		{
			return new LocationEntities(ConfigurationManager.ConnectionStrings["LocationEntities"].ConnectionString);
		}
	}		


    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<NAT_LS_Address_Geography> NAT_LS_Address_Geography { get; set; }

    public virtual DbSet<NAT_LS_Deal_Site_Location_Association_Table> NAT_LS_Deal_Site_Location_Association_Table { get; set; }

    public virtual DbSet<NAT_LS_Location> NAT_LS_Location { get; set; }

    public virtual DbSet<NAT_LS_LOCATION_VW> NAT_LS_LOCATION_VW { get; set; }

    public virtual DbSet<NAT_LS_LOCATION_GRID_VW> NAT_LS_LOCATION_GRID_VW { get; set; }

}

}

