
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nat.LocationApp.Models.EFModel
{

using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
public partial class NAT_LS_LOCATION_GRID_VW : Entity
{

    public Nullable<int> Country_ID { get; set; }

    public string Country_Name { get; set; }

    public string Country_Code { get; set; }

    public Nullable<int> Province_ID { get; set; }

    public string Province_Name { get; set; }

    public string Province_Code { get; set; }

    public Nullable<decimal> Tax_Rate_1 { get; set; }

    public Nullable<decimal> Tax_Rate_2 { get; set; }

    public Nullable<decimal> Tax_Rate_3 { get; set; }

    public Nullable<decimal> Tax_Rate_4 { get; set; }

    public Nullable<decimal> Tax_Rate_5 { get; set; }

    public int City_ID { get; set; }

    public string City_Name { get; set; }

    public string City_Code { get; set; }

    public bool Active { get; set; }

    public Nullable<System.DateTime> Last_Updated_Date { get; set; }

    public string Last_Updated_By { get; set; }

    public Nullable<int> Legal_Drinking_Age { get; set; }

    public Nullable<decimal> Virtual_Tax { get; set; }

    public Nullable<decimal> Total_In_Person_Tax { get; set; }

    public string Market_ID { get; set; }

    public string Location_Short_Code { get; set; }

    public string StateCode { get; set; }

    public string CountryCode { get; set; }

    public string DST_Time { get; set; }

    public string DST_Zone_Code { get; set; }

    public string Standard_Time { get; set; }

    public string Standard_Timezone_Code { get; set; }

    public string Manager_Name { get; set; }

    public string Manager_Number { get; set; }

    public string Manager_Email { get; set; }

    public string Tax_Rate_1_Label { get; set; }

    public string Tax_Rate_2_Label { get; set; }

    public string Tax_Rate_3_Label { get; set; }

    public string Tax_Rate_4_Label { get; set; }

    public string Tax_Rate_5_Label { get; set; }

    public string City_Short_Name { get; set; }

}

}
