
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nat.LocationApp.Models.EFModel
{

using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
public partial class NAT_LS_Location : Entity
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NAT_LS_Location()
    {

        this.NAT_LS_Deal_Site_Location_Association_Table = new HashSet<NAT_LS_Deal_Site_Location_Association_Table>();

    }


    public int Location_ID { get; set; }

    public string Parent_Location_Code { get; set; }

    public string Location_Name { get; set; }

    public string Location_Description { get; set; }

    public string Location_Short_Code { get; set; }

    public string Location_Type_LKP { get; set; }

    public bool Active_Flag { get; set; }

    public Nullable<bool> Sales_Tax_Applicable_Flag { get; set; }

    public Nullable<bool> Sales_Tax_Inclusive_Flag { get; set; }

    public Nullable<decimal> Tax_Rate { get; set; }

    public string Facebook_Url { get; set; }

    public string Twitter_Url { get; set; }

    public string Instagram_Url { get; set; }

    public Nullable<int> Address_Id { get; set; }

    public Nullable<decimal> Supplies_Tax { get; set; }

    public Nullable<decimal> State_Tax { get; set; }

    public System.DateTime Created_Date { get; set; }

    public string Created_By { get; set; }

    public Nullable<System.DateTime> Last_Updated_Date { get; set; }

    public string Last_Updated_By { get; set; }

    public string Timezone { get; set; }

    public string Stripe_Api_Key { get; set; }

    public Nullable<int> Precision { get; set; }

    public string Currency { get; set; }

    public string Airport_Code { get; set; }

    public string Google_Short_Code { get; set; }

    public Nullable<decimal> Tax_3 { get; set; }

    public Nullable<decimal> Tax_4 { get; set; }

    public Nullable<decimal> Tax_5 { get; set; }

    public Nullable<bool> Daylight_Saving_Applicable { get; set; }

    public Nullable<System.DateTime> Daylight_Start_Time { get; set; }

    public Nullable<System.DateTime> Daylight_End_Time { get; set; }

    public string Market_ID { get; set; }

    public Nullable<long> Manager_ID { get; set; }

    public Nullable<decimal> Virtual_Tax { get; set; }

    public Nullable<int> Legal_Drinking_Age { get; set; }

    public string State_Tax_Label { get; set; }

    public string Tax_Rate_Label { get; set; }

    public string Tax_3_Label { get; set; }

    public string Tax_4_Label { get; set; }

    public string Tax_5_Label { get; set; }

    public string Virtual_Tax_Label { get; set; }

    public Nullable<bool> Tax_Rate_Include { get; set; }

    public Nullable<bool> State_Tax_Include { get; set; }

    public Nullable<bool> Tax_3_Include { get; set; }

    public Nullable<bool> Tax_4_Include { get; set; }

    public Nullable<bool> Tax_5_Include { get; set; }

    public string Virtual_Tax_Area { get; set; }

    public string Tax_Rate_Area { get; set; }

    public string Tax_3_Area { get; set; }

    public string Tax_4_Area { get; set; }

    public string Tax_5_Area { get; set; }

    public string URL { get; set; }

    public string Virtual_Tax_Include { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<NAT_LS_Deal_Site_Location_Association_Table> NAT_LS_Deal_Site_Location_Association_Table { get; set; }

}

}
