
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nat.LocationApp.Models.EFModel
{

using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
public partial class NAT_LS_Address_Geography : Entity
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NAT_LS_Address_Geography()
    {

        this.NAT_LS_Address_Geography_Children = new HashSet<NAT_LS_Address_Geography>();

    }


    public int Address_Geography_ID { get; set; }

    public string Parent_Geography_Code { get; set; }

    public string Geography_Name { get; set; }

    public string Geography_Description { get; set; }

    public string Geography_Short_Code { get; set; }

    public string Geography_Type_LKP { get; set; }

    public System.DateTime Created_Date { get; set; }

    public string Created_By { get; set; }

    public Nullable<System.DateTime> Last_Updated_Date { get; set; }

    public string Last_Updated_By { get; set; }

    public bool Active_Flag { get; set; }

    public Nullable<int> Parent_Geography_ID { get; set; }

    public string New_Parent_Code { get; set; }

    public string New_Geography_Code { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<NAT_LS_Address_Geography> NAT_LS_Address_Geography_Children { get; set; }

    public virtual NAT_LS_Address_Geography NAT_LS_Address_Geography_Parent { get; set; }

}

}
