
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nat.LocationApp.Models.EFModel
{

using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
public partial class NAT_LS_Deal_Site_Location_Association_Table : Entity
{

    public int Deal_Site_ID { get; set; }

    public int Location_ID { get; set; }

    public decimal Sales_Tax_Collected { get; set; }

    public System.DateTime Created_Date { get; set; }

    public string Created_By { get; set; }

    public Nullable<System.DateTime> Last_Updated_Date { get; set; }

    public string Last_Updated_By { get; set; }

    public bool Active_Flag { get; set; }



    public virtual NAT_LS_Location NAT_LS_Location { get; set; }

}

}
