//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.AuthApp.Models.EFModel
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class AuthEntities : ElasticScaleContext
    {
        private void Initialize(){
    			}
    
        private AuthEntities(string connectionStringName)
            : base(connectionStringName)
        {
    		Initialize();
        }
    
    	private AuthEntities()
            : base()
        {
    		Initialize();
        }
    
    	public static AuthEntities CreateContext(bool isMultitenancyEnabled = false)
    	{
    		if(isMultitenancyEnabled)	
    		{
    			return new AuthEntities();
    		}
    		else
    		{
    			return new AuthEntities(ConfigurationManager.ConnectionStrings["AuthEntities"].ConnectionString);
    		}
    	}
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public virtual DbSet<NAT_AUS_External_Identity> NAT_AUS_External_Identity { get; set; }
        public virtual DbSet<NAT_AUS_Notification_Preference> NAT_AUS_Notification_Preference { get; set; }
        public virtual DbSet<NAT_AUS_Privilege> NAT_AUS_Privilege { get; set; }
        public virtual DbSet<NAT_AUS_Role> NAT_AUS_Role { get; set; }
        public virtual DbSet<NAT_AUS_Role_Privilege_Mapping> NAT_AUS_Role_Privilege_Mapping { get; set; }
        public virtual DbSet<NAT_AUS_User_Role_Mapping> NAT_AUS_User_Role_Mapping { get; set; }
        public virtual DbSet<NAT_AUS_User> NAT_AUS_User { get; set; }
        public virtual DbSet<NAT_AUS_User_Location_Mapping> NAT_AUS_User_Location_Mapping { get; set; }
        public virtual DbSet<NAT_USERS_VW> NAT_USERS_VW { get; set; }
    }
}
