//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.AuthApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_USERS_VW : Entity
    {
        public Nullable<long> Parent_User_ID { get; set; }
        public string User_Name { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public long User_ID { get; set; }
        public string User_Image_URL { get; set; }
        public string Reference_Type_LKP { get; set; }
        public Nullable<long> Reference_ID { get; set; }
        public string Phone_Number { get; set; }
        public string Email { get; set; }
        public string Last_Updated_By { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public Nullable<bool> Active_Flag { get; set; }
        public string Role_Name { get; set; }
        public string Location_Code { get; set; }
        public long Role_ID { get; set; }
    }
}
