//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.AuthApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_AUS_Role : Entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NAT_AUS_Role()
        {
            this.NAT_AUS_Role_Privilege_Mapping = new HashSet<NAT_AUS_Role_Privilege_Mapping>();
            this.NAT_AUS_User_Role_Mapping = new HashSet<NAT_AUS_User_Role_Mapping>();
        }
    
        public long Role_ID { get; set; }
        public string Role_Code { get; set; }
        public string Role_Name { get; set; }
        public string Role_Description { get; set; }
        public string Role_Type { get; set; }
        public bool Active_Flag { get; set; }
        public Nullable<System.DateTime> Effective_Start_Date { get; set; }
        public Nullable<System.DateTime> Effective_End_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Last_Updated_By { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_AUS_Role_Privilege_Mapping> NAT_AUS_Role_Privilege_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_AUS_User_Role_Mapping> NAT_AUS_User_Role_Mapping { get; set; }
    }
}
