//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.PaintingApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_PS_Painting_Supply: Entity
    {
        public int Painting_Supply_ID { get; set; }
        public Nullable<int> Painting_Video_ID { get; set; }
        public string Item_Name { get; set; }
        public string Quantity { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public string Last_Updated_By { get; set; }
    
        public virtual NAT_PS_Painting_Video NAT_PS_Painting_Video { get; set; }
    }
}
