//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.PaintingApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_PS_Painting_Image: Entity
    {
        public int Painting_Image_ID { get; set; }
        public Nullable<int> Painting_ID { get; set; }
        public Nullable<int> Image_Type_LKP_ID { get; set; }
        public string Image_Path { get; set; }
        public Nullable<System.DateTime> Effective_Start_Date { get; set; }
        public Nullable<System.DateTime> Effective_End_Date { get; set; }
        public string Public_URL { get; set; }
        public Nullable<int> Number_of_Major_Steps { get; set; }
        public Nullable<int> Time_To_Complete { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Width { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public string Last_Updated_By { get; set; }
        public bool Active_Flag { get; set; }
        public string Original_Image_Path { get; set; }
    
        public virtual NAT_PS_Painting NAT_PS_Painting { get; set; }
    }
}
