//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.PaintingApp.Models.EFModel
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class PaintingEntities : ElasticScaleContext
    {
    private void Initialize(){
    			}
    
        private PaintingEntities(string connectionStringName)
            : base(connectionStringName)
        {
    		Initialize();
        }
    
    	private PaintingEntities()
            : base()
        {
    		Initialize();
        }
    
    	public static PaintingEntities CreateContext(bool isMultitenancyEnabled = false)
    	{
    		if(isMultitenancyEnabled)	
    		{
    			return new PaintingEntities();
    		}
    		else
    		{
    			return new PaintingEntities(ConfigurationManager.ConnectionStrings["PaintingEntities"].ConnectionString);
    		}
    	}
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NAT_PS_Painting_Rating> NAT_PS_Painting_Rating { get; set; }
        public virtual DbSet<NAT_PS_Painting_Rating_Log> NAT_PS_Painting_Rating_Log { get; set; }
        public virtual DbSet<NAT_Painting_Kit_Item> NAT_Painting_Kit_Item { get; set; }
        public virtual DbSet<NAT_PS_Painting_Attachment> NAT_PS_Painting_Attachment { get; set; }
        public virtual DbSet<NAT_PS_Painting_Event> NAT_PS_Painting_Event { get; set; }
        public virtual DbSet<NAT_PS_Painting> NAT_PS_Painting { get; set; }
        public virtual DbSet<NAT_PS_Painting_Requests> NAT_PS_Painting_Requests { get; set; }
        public virtual DbSet<NAT_PS_Painting_Image> NAT_PS_Painting_Image { get; set; }
        public virtual DbSet<NAT_PS_Painting_Supply> NAT_PS_Painting_Supply { get; set; }
        public virtual DbSet<NAT_PS_Painting_Video> NAT_PS_Painting_Video { get; set; }
    }
}
