//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.EventApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_TICKET_SUMMARY_VW : Entity
    {
        public string Event_Code { get; set; }
        public string Seat_Type { get; set; }
        public string Ticket_Status { get; set; }
        public Nullable<int> Ticket_Count { get; set; }
        public Nullable<int> Total_Seats { get; set; }
        public long ID { get; set; }
        public Nullable<decimal> Ticket_Price { get; set; }
        public Nullable<int> Checked_In_Ticket_Count { get; set; }
    }
}
