//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.EventApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_ES_Event : Entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NAT_ES_Event()
        {
            this.NAT_ES_Event_Feedback = new HashSet<NAT_ES_Event_Feedback>();
            this.NAT_ES_Event_Facility = new HashSet<NAT_ES_Event_Facility>();
            this.NAT_ES_Event_Seating_Plan = new HashSet<NAT_ES_Event_Seating_Plan>();
            this.NAT_ES_Event_Ticket_Price = new HashSet<NAT_ES_Event_Ticket_Price>();
            this.NAT_ES_Event_Wait_List = new HashSet<NAT_ES_Event_Wait_List>();
            this.NAT_ES_Event_Image = new HashSet<NAT_ES_Event_Image>();
            this.NAT_ES_Event_Iteration = new HashSet<NAT_ES_Event_Iteration>();
        }
    
        public int Event_ID { get; set; }
        public Nullable<int> Artist_ID { get; set; }
        public int Event_Type_LKP_ID { get; set; }
        public int Event_Status_LKP_ID { get; set; }
        public int Painting_ID { get; set; }
        public Nullable<int> Seating_Plan_ID { get; set; }
        public string Location_Code { get; set; }
        public string Venue_City_Code { get; set; }
        public Nullable<int> Event_Age_Group_Type_LKP_ID { get; set; }
        public Nullable<int> Event_Category_LKP_ID { get; set; }
        public Nullable<int> Venue_ID { get; set; }
        public Nullable<int> Venue_Hall_ID { get; set; }
        public string Event_Name { get; set; }
        public Nullable<decimal> Max_Ticket_Price { get; set; }
        public Nullable<decimal> Min_Ticket_Price { get; set; }
        public Nullable<bool> Is_Featured { get; set; }
        public string Event_Code { get; set; }
        public Nullable<System.DateTime> Effective_Start_Date { get; set; }
        public Nullable<System.DateTime> Effective_End_Date { get; set; }
        public Nullable<System.DateTime> Event_Date { get; set; }
        public Nullable<System.DateTime> Event_Start_Time { get; set; }
        public Nullable<System.DateTime> Event_End_Time { get; set; }
        public Nullable<bool> Private_Event_Flag { get; set; }
        public Nullable<bool> Fundraising_Event_Flag { get; set; }
        public string Event_Description { get; set; }
        public string Event_Tags { get; set; }
        public string Note_To_VCP { get; set; }
        public bool Virtual { get; set; }
        public string Google_Hangout_URL { get; set; }
        public Nullable<int> Capacity { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public string Last_Updated_By { get; set; }
        public bool Active_Flag { get; set; }
        public Nullable<System.DateTime> Painting_Updated_Date { get; set; }
        public bool Mark_For_Painting_Change { get; set; }
        public bool Auto_Painting { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_ES_Event_Feedback> NAT_ES_Event_Feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_ES_Event_Facility> NAT_ES_Event_Facility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_ES_Event_Seating_Plan> NAT_ES_Event_Seating_Plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_ES_Event_Ticket_Price> NAT_ES_Event_Ticket_Price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_ES_Event_Wait_List> NAT_ES_Event_Wait_List { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_ES_Event_Image> NAT_ES_Event_Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_ES_Event_Iteration> NAT_ES_Event_Iteration { get; set; }
    }
}
