//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.EventApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_ES_Event_Seating_Plan : Entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NAT_ES_Event_Seating_Plan()
        {
            this.NAT_ES_Event_Seat = new HashSet<NAT_ES_Event_Seat>();
        }
    
        public int Seating_Plan_ID { get; set; }
        public Nullable<int> Event_ID { get; set; }
        public string Event_Seating_Plan_Name { get; set; }
        public Nullable<int> Total_Seats { get; set; }
        public Nullable<System.DateTime> Effective_Start_Date { get; set; }
        public Nullable<System.DateTime> Effective_End_Date { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public string Last_Updated_By { get; set; }
        public bool Active_Flag { get; set; }
        public Nullable<bool> Default_Plan { get; set; }
        public string Background_Image { get; set; }
        public Nullable<int> Reference_ID { get; set; }
    
        public virtual NAT_ES_Event NAT_ES_Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_ES_Event_Seat> NAT_ES_Event_Seat { get; set; }
    }
}
