//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.EventApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_BOOKED_TICKET_VW : Entity
    {
        public int Booking_ID { get; set; }
        public string Ticket_Code { get; set; }
        public string Row_Number { get; set; }
        public string Seat_Number { get; set; }
        public string Cancellation_Reason { get; set; }
        public string Ticket_Type_LKP { get; set; }
        public string Ticket_Type { get; set; }
        public string Status_LKP { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Email { get; set; }
        public string Customer_Contact { get; set; }
        public Nullable<int> Customer_Age { get; set; }
        public string Image_Url { get; set; }
        public Nullable<bool> Checked_In { get; set; }
        public Nullable<System.DateTime> Checked_In_Time { get; set; }
        public Nullable<int> Checked_In_By { get; set; }
        public string QRCode_Image_Url { get; set; }
        public Nullable<int> Event_Painting_ID { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public string Last_Updated_By { get; set; }
        public bool Active_Flag { get; set; }
        public Nullable<bool> Has_Disability { get; set; }
        public Nullable<System.DateTime> Booking_Date { get; set; }
        public string Booking_Number { get; set; }
        public string Event_Code { get; set; }
        public Nullable<int> Invoice_ID { get; set; }
        public string Event_Name { get; set; }
        public Nullable<System.DateTime> Event_Start_Time { get; set; }
        public Nullable<System.DateTime> Event_End_Time { get; set; }
        public Nullable<int> Event_ID { get; set; }
        public string Location_Code { get; set; }
        public Nullable<bool> Virtual { get; set; }
        public string EventStatus { get; set; }
        public int Ticket_ID { get; set; }
    }
}
