//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.EventApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_ES_Event_Iteration : Entity
    {
        public long Iteration_ID { get; set; }
        public int Iteration_Status { get; set; }
        public int Event_ID { get; set; }
        public string Value { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Created_By { get; set; }
    
        public virtual NAT_ES_Event NAT_ES_Event { get; set; }
    }
}
