//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.EventApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_ES_Event_Wait_List : Entity
    {
        public int Event_Wait_List_ID { get; set; }
        public int Event_ID { get; set; }
        public int Customer_ID { get; set; }
        public string Event_Wait_List_Name { get; set; }
        public System.DateTime Effective_Start_Date { get; set; }
        public System.DateTime Effective_End_Date { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public string Last_Updated_By { get; set; }
        public bool Active_Flag { get; set; }
    
        public virtual NAT_ES_Event NAT_ES_Event { get; set; }
    }
}
