//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.EventApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_ES_Event_Seat : Entity
    {
        public int Seat_ID { get; set; }
        public Nullable<int> Seating_Plan_ID { get; set; }
        public Nullable<int> Seat_Type_LKP_ID { get; set; }
        public Nullable<int> Seat_Allocation_Type_LKP_ID { get; set; }
        public string Row_Number { get; set; }
        public string Seat_Number { get; set; }
        public string Status_LKP { get; set; }
        public Nullable<System.DateTime> Effective_Start_Date { get; set; }
        public Nullable<System.DateTime> Effective_End_Date { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public string Last_Updated_By { get; set; }
        public bool Active_Flag { get; set; }
        public string Label { get; set; }
        public Nullable<int> Offset_X { get; set; }
        public Nullable<int> Offset_Y { get; set; }
        public Nullable<int> Radius { get; set; }
    
        public virtual NAT_ES_Event_Seating_Plan NAT_ES_Event_Seating_Plan { get; set; }
    }
}
