//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.CustomerApp.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using TLX.CloudCore.Patterns.Repository.Ef6;
    
    public partial class NAT_CS_Customer : Entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NAT_CS_Customer()
        {
            this.NAT_CS_Customer_Event = new HashSet<NAT_CS_Customer_Event>();
            this.NAT_CS_Customer_Following = new HashSet<NAT_CS_Customer_Following>();
            this.NAT_CS_Customer_Liked_Events = new HashSet<NAT_CS_Customer_Liked_Events>();
        }
    
        public int Customer_ID { get; set; }
        public Nullable<int> Customer_Status_LKP_ID { get; set; }
        public Nullable<System.DateTime> Effective_Start_Date { get; set; }
        public Nullable<System.DateTime> Effective_End_Date { get; set; }
        public Nullable<int> Gender_LKP_ID { get; set; }
        public Nullable<int> Residential_Address_ID { get; set; }
        public Nullable<int> Shopping_Address_ID { get; set; }
        public Nullable<int> Billing_Address_ID { get; set; }
        public string Person_First_Name { get; set; }
        public string Person_Last_Name { get; set; }
        public string Person_Middle_Name { get; set; }
        public string Person_Email { get; set; }
        public string Person_Profile_Image_Link { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Person_Extension { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public string Last_Updated_By { get; set; }
        public bool Active_Flag { get; set; }
        public Nullable<bool> Has_Disability { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_CS_Customer_Event> NAT_CS_Customer_Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_CS_Customer_Following> NAT_CS_Customer_Following { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NAT_CS_Customer_Liked_Events> NAT_CS_Customer_Liked_Events { get; set; }
        public virtual NAT_CS_Customer_Address NAT_CS_Customer_Residential_Address { get; set; }
        public virtual NAT_CS_Customer_Address NAT_CS_Customer_Shipping_Address { get; set; }
        public virtual NAT_CS_Customer_Address NAT_CS_Customer_Billing_Address { get; set; }
    }
}
